---

- name: ensuring elasticsearch is started
  service:
    name: elasticsearch
    state: started
  tags:
    - elasticsearch

- name: installing ingest-attachment plugin for elasticsearch
  elasticsearch_plugin:
    name: ingest-attachment
    state: present
    force: yes
  notify: restart elasticsearch
  tags:
    - elasticsearch
    - elasticsearch-plugins

...
