---

- name: prepare custom repos
  import_tasks: yumrepos.yml
  tags:
    - elasticsearch
    - zammad
    - yumrepos

- name: installation steps
  import_tasks: install.yml
  tags:
    - elasticsearch
    - java
    - yum
    - zammad

- name: elasticsearch for zammad details
  import_tasks: elasticsearch.yml
  tags:
    - elasticsearch

- name: include config changes
  include_tasks: config.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

...
