---

- name: prepare custom repos
  import_tasks: yumrepos.yml
  tags:
    - elasticsearch
    - zammad
    - yumrepos

- name: installation steps
  import_tasks: install.yml
  tags:
    - elasticsearch
    - java
    - yum
    - zammad

- name: create zammad ssl dir
  file:
    path: "{{ zammad_ssl_dir }}"
    state: directory
    mode: 0750
    owner: root
    group: nginx

- name: copy cert from localhost to system
  command:
    argv:
      - scp
      - '{{ zammad_ssl_cert_key_local_path }}/{{ zammad_ssl_cert_key }}'
      - '{{ zammad_ssl_cert_local_path }}/{{ zammad_ssl_cert }}'
      - '{{ ansible_fqdn }}:{{ zammad_ssl_dir }}'
  delegate_to: localhost
  when: zammad_cert_installation == 'yes'

- name: set correct file group ownership to cert files
  file:
    path: '{{ zammad_ssl_dir }}/{{ item }}'
    group: nginx
  loop:
    - '{{ zammad_ssl_cert }}'
    - '{{ zammad_ssl_cert_key }}'
    
- name: elasticsearch for zammad details
  import_tasks: elasticsearch.yml
  tags:
    - elasticsearch

- name: include config changes
  include_tasks: config.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

...
