---

- name: install elasticsearch yum repo
  yum_repository:
    baseurl: "https://artifacts.elastic.co/packages/7.x/yum"
    gpgcheck: yes
    gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    enabled: yes
    name: "elasticsearch-7.x"
    description: "Elasticsearch repository for 7.x packages"
    skip_if_unavailable: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: install zammad yum repo
  yum_repository:
    baseurl: "https://dl.packager.io/srv/rpm/zammad/zammad/stable/el/7/x86_64"
    gpgcheck: no
    repo_gpgcheck: yes
    gpgkey: "https://dl.packager.io/srv/zammad/zammad/key"
    enabled: yes
    name: "zammad"
    description: "Repository for zammad/zammad (stable) packages."
    skip_if_unavailable: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

...
