---

- name: restart zammad nginx
  service:
    name: nginx
    state: restarted

- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted

- name: config elasticsearch for zammad
  command: zammad run rails r "Setting.set('es_url', 'http://127.0.0.1:9200')"

- name: rebuild zammad elasticsearch searchindex
  command: 'zammad run rake searchindex:rebuild'

...
